### ISSUE TITLE
Camera Issue

### ISSUE THREAD

**Issue by sonderchild** [omnirom/android_device_samsung_tuna#1]
Hi,
Unfortunately, the **camera** still appears to be crashing randomly. It works, when the device boots out of  **"power off**"-state (just a **restart** is insufficient) for a couple of minutes maybe hours.
This is a problem, all **Android 6** ROMs have in common. Is there something that can be done about it?

In addition, the **flashlight** will not work as well. I have tried to record an error log, but no errors are recorded :-/ 

Regards

**Comment by humberos** [comment]
Please use http://jira.omnirom.org .
Thank you.
